# Generated by Django 4.1.1 on 2022-09-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="geodatapacket",
            name="dev",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
