# Generated by Django 4.1.1 on 2022-09-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_geodatapacket_dev"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geodatapacket",
            name="activity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="geodatapacket",
            name="cil_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geodatapacket",
            name="dev",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="geodatapacket",
            name="floor_label",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geodatapacket",
            name="hor_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geodatapacket",
            name="identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="geodatapacket",
            name="timestamp",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geodatapacket",
            name="ver_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
