# Generated by Django 4.1.1 on 2022-09-23 19:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_alter_geodatapacket_activity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geodatapacket",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=3857),
        ),
    ]
